routes/admin.php
<?php
Route::prefix('madmin')->name('admin.')->middleware('auth')->group(function() {
    Route::get('dashboard', 'Admin\HomeController@index');

    Route::prefix('users')->name('user.')->group(function() {
        Route::get('/', 'Admin\UserController@index')->name('index');
        Route::get('/add', 'Admin\UserController@create')->name('add');
        Route::post('/add', 'Admin\UserController@store');
        Route::get('/show/{id}', 'Admin\UserController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\UserController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\UserController@update');
        Route::get('/delete/{id}', 'Admin\UserController@delete')->name('delete');
    });

    Route::prefix('administrators')->name('admin.')->group(function() {
        Route::get('/', 'Admin\AdminController@index')->name('index');
        Route::get('/add', 'Admin\AdminController@create')->name('add');
        Route::post('/add', 'Admin\AdminController@store');
        Route::get('/show/{id}', 'Admin\AdminController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\AdminController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\AdminController@update');
        Route::get('/delete/{id}', 'Admin\AdminController@delete')->name('delete');
    });

    Route::prefix('category')->name('category.')->group(function() {
        Route::get('/', 'Admin\CategoryController@index')->name('index');
        Route::get('/add', 'Admin\CategoryController@create')->name('add');
        Route::post('/add', 'Admin\CategoryController@store');
        Route::get('/show/{id}', 'Admin\CategoryController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\CategoryController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\CategoryController@update');
        Route::get('/delete/{id}', 'Admin\CategoryController@delete')->name('delete');
    });

    Route::prefix('catalog')->name('catalog.')->group(function() {
        Route::get('/', 'Admin\CatalogController@index')->name('index');
        Route::get('/add', 'Admin\CatalogController@create')->name('add');
        Route::post('/add', 'Admin\CatalogController@store');
        Route::get('/show/{id}', 'Admin\CatalogController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\CatalogController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\CatalogController@update');
        Route::get('/delete/{id}', 'Admin\CatalogController@delete')->name('delete');
    });

    Route::prefix('posts')->name('post.')->group(function() {
        Route::get('/', 'Admin\PostController@index')->name('index');
        Route::get('/add', 'Admin\PostController@create')->name('add');
        Route::post('/add', 'Admin\PostController@store');
        Route::get('/show/{id}', 'Admin\PostController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\PostController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\PostController@update');
        Route::get('/delete/{id}', 'Admin\PostController@delete')->name('delete');
    });

    Route::prefix('hosting')->name('hosting.')->group(function() {
        Route::get('/', 'Admin\HostingController@index')->name('index');
        Route::get('/add', 'Admin\HostingController@create')->name('add');
        Route::post('/add', 'Admin\HostingController@store');
        Route::get('/show/{id}', 'Admin\HostingController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\HostingController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\HostingController@update');
        Route::get('/delete/{id}', 'Admin\HostingController@delete')->name('delete');
    });

    Route::prefix('vps')->name('vps.')->group(function() {
        Route::get('/', 'Admin\VPSController@index')->name('index');
        Route::get('/add', 'Admin\VPSController@create')->name('add');
        Route::post('/add', 'Admin\VPSController@store');
        Route::get('/show/{id}', 'Admin\VPSController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\VPSController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\VPSController@update');
        Route::get('/delete/{id}', 'Admin\VPSController@delete')->name('delete');
    });

    Route::prefix('dedicated')->name('dedicated.')->group(function() {
        Route::get('/', 'Admin\ServerController@index')->name('index');
        Route::get('/add', 'Admin\ServerController@create')->name('add');
        Route::post('/add', 'Admin\ServerController@store');
        Route::get('/show/{id}', 'Admin\ServerController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\ServerController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\ServerController@update');
        Route::get('/delete/{id}', 'Admin\ServerController@delete')->name('delete');
    });

    Route::prefix('rack')->name('rack.')->group(function() {
        Route::get('/', 'Admin\RackController@index')->name('index');
        Route::get('/add', 'Admin\RackController@create')->name('add');
        Route::post('/add', 'Admin\RackController@store');
        Route::get('/show/{id}', 'Admin\RackController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\RackController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\RackController@update');
        Route::get('/delete/{id}', 'Admin\RackController@delete')->name('delete');
    });

    Route::prefix('colocation')->name('colocation.')->group(function() {
        Route::get('/', 'Admin\ColocationController@index')->name('index');
        Route::get('/add', 'Admin\ColocationController@create')->name('add');
        Route::post('/add', 'Admin\ColocationController@store');
        Route::get('/show/{id}', 'Admin\ColocationController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\ColocationController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\ColocationController@update');
        Route::get('/delete/{id}', 'Admin\ColocationController@delete')->name('delete');
    });

    Route::prefix('nwall')->name('nwall.')->group(function() {
        Route::get('/', 'Admin\NWallController@index')->name('index');
        Route::get('/add', 'Admin\NWallController@create')->name('add');
        Route::post('/add', 'Admin\NWallController@store');
        Route::get('/show/{id}', 'Admin\NWallController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\NWallController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\NWallController@update');
        Route::get('/delete/{id}', 'Admin\NWallController@delete')->name('delete');
    });

    Route::prefix('seo')->name('seo.')->group(function() {
        Route::get('/', 'Admin\SeoController@index')->name('index');
        Route::get('/add', 'Admin\SeoController@create')->name('add');
        Route::post('/add', 'Admin\SeoController@store');
        Route::get('/show/{id}', 'Admin\SeoController@show');
        Route::get('/edit/{id}', 'Admin\SeoController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\SeoController@update');
        Route::get('/delete/{id}', 'Admin\SeoController@delete')->name('delete');
    });

    Route::prefix('pages')->name('pages.')->group(function() {
        Route::get('/', 'Admin\PageController@index')->name('index');
        Route::get('/add', 'Admin\PageController@create')->name('add');
        Route::post('/add', 'Admin\PageController@store');
        Route::get('/show/{id}', 'Admin\PageController@show');
        Route::get('/edit/{id}', 'Admin\PageController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\PageController@update');
        Route::get('/delete/{id}', 'Admin\PageController@delete')->name('delete');
    });

    Route::prefix('config')->name('config.')->group(function() {
        Route::get('/', 'Admin\ConfigController@index');
        Route::get('/homepage', 'Admin\ConfigController@show_homepage')->name('show_homepage');
        Route::get('/homepage/{id}', 'Admin\ConfigController@edit_homepage')->name('edit_homepage');
        Route::post('/homepage/{id}', 'Admin\ConfigController@update_homepage');
    });
});

routes/web.php
<?php
use App\Http\Controllers\Helper\MAC;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::get('/mlogin', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/mlogin', 'Auth\LoginController@login');
// Route::get('/mregister', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('/mregister/', 'Auth\RegisterController@register');
// Route::get('/mpassword/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
// Route::post('/mpassword/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
// Route::get('/mpassword/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
// Route::post('/mpassword/reset', 'Auth\ResetPasswordController@reset');
Route::get('/logout', 'AuthController@logout')->name('logout');

include base_path('routes/admin.php');
// include base_path('routes/view.php');



Route::get('/', 'Website\HomeController@index')->name('home');
Route::get('su-kien/du-doan-ty-so-viet-nam-malaysia.html', 'Website\HomeController@event');
Route::get('su-kien/du-doan-ket-qua-viet-nam-malaysia.html', 'Website\HomeController@bongda');
Route::get('su-kien/du-doan-ket-qua-viet-nam-indo.html', 'Website\HomeController@vnindo');
// Route::get('/hosting.html', 'Website\HomeController@hosting');
// Route::get('/vps.html', 'Website\HomeController@hosting');
// Route::get('/dedicated.html', 'Website\HomeController@hosting');
// Route::get('/tu-rack.html', 'Website\HomeController@hosting');
Route::get('/2019/04/17/anti-ddos-la-gi', function() {
    return redirect('https://www.nps.vn/kb/blogs/kien-thuc/anti-ddos/dos-ddos-la-gi-cach-chong-hacker-ddos-nhu-the-nao.html');
});

Route::get('/{slug}.html', 'Website\HomeController@page');
// Route::get('/sitemapnps.xml', 'Website\HomeController@xml');
// $segment = '';
// $page = Request::segment(1);
// if (!empty($page)) {
// 	$segment = MAC::redirect_page($page);

// 	if ($segment->status == 200) {
// 		dd($page);
// 		Route::get('/'.$page, 'Website\HomeController@page')->name('page');
// 	}else{
// 		Route::get('/404');
// 	}
// }else{
// 	Route::get('/404');
// }

app/Http/Controllers/Admin/ConfigController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use Session;

class ConfigController extends Controller
{
    public function index()
    {
    	return view('admin.config.index');
    }

    public function show_homepage()
    {
    	$config_data = [];
    	$config_name = [];
        $config_page = [];
    	$data = [];
        foreach (config('widget') as $item) {
            foreach ($item as $key => $val) {
                $config_page[$key] = $val;
            }
        }
    	foreach ($config_page as $item => $element) {
    		$config_widget[$item]['label'] = $element['label'];
    		foreach ($element['data'] as $key => $val) {
    			$config_data[] = $val;
    			$config_widget[$item]['data'][$key] = $val['name'];
    		}
    	}
    	$list['config_widget'] = $config_widget;
    	$config_db = DB::table('config')->select('name')->get();
    	foreach ($config_db as $item) {
    		$config_name[] = $item->name;
    	}
    	foreach ($config_data as $item) {
    		if (!in_array($item['name'], $config_name)) {
    			$data[] = $item;
    		}
    	}
    	if (!empty($data)) {
    		DB::table('config')->insert($data);
    	}
    	$list['list'] = DB::table('config')->select('id', 'name', 'label')->get();
    	return view('admin.config.homepage', $list);
    }

    public function edit_homepage($id)
    {
    	$value = DB::table('config')->where('id', $id)->first();
    	if (!empty($value)) {
    		$data['data'] = $value;
    		return view('admin.config.edit_homepage', $data);
    	}
    	Session::flash('status', 'danger');
        Session::flash('notify', 'Không có giá trị này!');
        return redirect()->route('admin.config.homepage');
    }

    public function update_homepage(Request $request, $id)
    {
    	$value = DB::table('config')->where('id', $id)->first();
    	if (!empty($value)) {
    		$rules = [
	            'name'	=> 'required|max:250',
	        ];

	        $messages = config('lang.vi');
	        $this->validate($request, $rules, $messages);
    		$data = [
    			'label' => $request->name,
    			'value' => $request->value
    		];
    		DB::table('config')->where('id', $id)->update($data);
    		Session::flash('status', 'success');
	        Session::flash('notify', 'Cập nhật giá trị thành công!');
    		return redirect()->back();
    	}
    	Session::flash('status', 'danger');
        Session::flash('notify', 'Không có giá trị này!');
        return redirect()->route('admin.config.homepage');
    }
}

resources/views/admin/config/edit_homepage.blade.php
@extends('admin.home')
@section('content')
<script src="/js/ckeditor.js"></script>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-9 card_title">
							<h4>Cập nhật giá trị {{ $data->label }}</h4>
						</div>
						<div class="col-md-3">
							<a class="btn btn-light" href="{{ route('admin.config.show_homepage') }}" title="">Back to Config Homepage</a>
						</div>
					</div>
				</div>
				@include('admin.notify')
				<div class="card-body">
					<form action="" method="post" accept-charset="utf-8">
						@csrf
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Name</label>
								<input type="text" name="name" class="form-control input_mac" value="{{ $data->label }}" maxlength="250" required="">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<select name="type" class="form-control select_mac" disabled="">
									<option value="label" class="option_mac" {{ @($data->type == 'label') ? 'selected' : '' }}>Label</option>
									<option value="link" class="option_mac" {{ @($data->type == 'link') ? 'selected' : '' }}>Link</option>
									<option value="text" class="option_mac" {{ @($data->type == 'text') ? 'selected' : '' }}>Text</option>
								</select>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-12 px-0 form_mac">
								@if ($data->type == 'text')
								<textarea id="editor" name="value" class="form-control input_mac" rows="1" maxlength="2000">{!! $data->value !!}</textarea>
								@else
								<label class="label_mac">Value</label>
								<input type="text" name="value" class=" form-control input_mac" value="{{ $data->value }}" maxlength="250">
								@endif
							</div>
						</div>
						<div class="form-group text-right">
							<button type="submit" class="btn">Cập nhật</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	
	ClassicEditor
        .create( document.querySelector( '#editor' ),{
        	toolbar: [
	            'heading', '|', 'custombutton', 'bold', 'italic', 'bulletedList', 'numberedList', 'blockQuote', 'link', 'alignment'
	        ]
        } )
        .catch( error => {
            console.error( error );
        } );
</script>
@endsection

resources/views/admin/config/homepage.blade.php
@php
	use App\Http\Controllers\Helper\MAC;
@endphp
@extends('admin.home')
@section('content')
<div class="container-fluid">
	<div class="row">
		@include('admin.notify')
		@foreach ($config_widget as $key => $element)
		<div class="col-md-4 pb-5">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>{{ $element['label'] }}</h4>
						</div>
					</div>
				</div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-hover table-striped">
							<tbody>
								@foreach ($list as $item)
								@if (in_array($item->name, $element['data']))
								<tr>
									<td><a href="{{ route('admin.config.show_homepage') }}" title="">{{ $item->label }}</a></td>
									<td class="text-right"><a href="{{ route('admin.config.edit_homepage', ['id' => $item->id]) }}" title=""><i class="fas fa-edit"></i></a></td>
								</tr>
								@endif
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		@endforeach
	</div>
</div>
@endsection

resources/views/admin/config/index.blade.php
@php
	use App\Http\Controllers\Helper\MAC;
@endphp
@extends('admin.home')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Giao diện</h4>
						</div>
					</div>
				</div>
				<div class="card-body">
					<div class="row">
						<div class="col-md-6">
							<a href="{{ route('admin.config.show_homepage') }}" title="">Trang chủ</a>
						</div>
						<div class="col-md-6 text-right">
							<a href="{{ route('admin.config.show_homepage') }}" title=""><i class="fas fa-edit"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection