routes/admin.php
<?php
Route::prefix('madmin')->name('admin.')->middleware('auth')->group(function() {
    Route::get('dashboard', 'Admin\HomeController@index');

    Route::prefix('users')->name('user.')->group(function() {
        Route::get('/', 'Admin\UserController@index')->name('index');
        Route::get('/add', 'Admin\UserController@create')->name('add');
        Route::post('/add', 'Admin\UserController@store');
        Route::get('/show/{id}', 'Admin\UserController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\UserController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\UserController@update');
        Route::get('/delete/{id}', 'Admin\UserController@delete')->name('delete');
    });

    Route::prefix('administrators')->name('admin.')->group(function() {
        Route::get('/', 'Admin\AdminController@index')->name('index');
        Route::get('/add', 'Admin\AdminController@create')->name('add');
        Route::post('/add', 'Admin\AdminController@store');
        Route::get('/show/{id}', 'Admin\AdminController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\AdminController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\AdminController@update');
        Route::get('/delete/{id}', 'Admin\AdminController@delete')->name('delete');
    });

    Route::prefix('category')->name('category.')->group(function() {
        Route::get('/', 'Admin\CategoryController@index')->name('index');
        Route::get('/add', 'Admin\CategoryController@create')->name('add');
        Route::post('/add', 'Admin\CategoryController@store');
        Route::get('/show/{id}', 'Admin\CategoryController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\CategoryController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\CategoryController@update');
        Route::get('/delete/{id}', 'Admin\CategoryController@delete')->name('delete');
    });

    Route::prefix('catalog')->name('catalog.')->group(function() {
        Route::get('/', 'Admin\CatalogController@index')->name('index');
        Route::get('/add', 'Admin\CatalogController@create')->name('add');
        Route::post('/add', 'Admin\CatalogController@store');
        Route::get('/show/{id}', 'Admin\CatalogController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\CatalogController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\CatalogController@update');
        Route::get('/delete/{id}', 'Admin\CatalogController@delete')->name('delete');
    });

    Route::prefix('posts')->name('post.')->group(function() {
        Route::get('/', 'Admin\PostController@index')->name('index');
        Route::get('/add', 'Admin\PostController@create')->name('add');
        Route::post('/add', 'Admin\PostController@store');
        Route::get('/show/{id}', 'Admin\PostController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\PostController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\PostController@update');
        Route::get('/delete/{id}', 'Admin\PostController@delete')->name('delete');
    });

    Route::prefix('hosting')->name('hosting.')->group(function() {
        Route::get('/', 'Admin\HostingController@index')->name('index');
        Route::get('/add', 'Admin\HostingController@create')->name('add');
        Route::post('/add', 'Admin\HostingController@store');
        Route::get('/show/{id}', 'Admin\HostingController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\HostingController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\HostingController@update');
        Route::get('/delete/{id}', 'Admin\HostingController@delete')->name('delete');
    });

    Route::prefix('vps')->name('vps.')->group(function() {
        Route::get('/', 'Admin\VPSController@index')->name('index');
        Route::get('/add', 'Admin\VPSController@create')->name('add');
        Route::post('/add', 'Admin\VPSController@store');
        Route::get('/show/{id}', 'Admin\VPSController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\VPSController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\VPSController@update');
        Route::get('/delete/{id}', 'Admin\VPSController@delete')->name('delete');
    });

    Route::prefix('dedicated')->name('dedicated.')->group(function() {
        Route::get('/', 'Admin\ServerController@index')->name('index');
        Route::get('/add', 'Admin\ServerController@create')->name('add');
        Route::post('/add', 'Admin\ServerController@store');
        Route::get('/show/{id}', 'Admin\ServerController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\ServerController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\ServerController@update');
        Route::get('/delete/{id}', 'Admin\ServerController@delete')->name('delete');
    });

    Route::prefix('rack')->name('rack.')->group(function() {
        Route::get('/', 'Admin\RackController@index')->name('index');
        Route::get('/add', 'Admin\RackController@create')->name('add');
        Route::post('/add', 'Admin\RackController@store');
        Route::get('/show/{id}', 'Admin\RackController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\RackController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\RackController@update');
        Route::get('/delete/{id}', 'Admin\RackController@delete')->name('delete');
    });

    Route::prefix('colocation')->name('colocation.')->group(function() {
        Route::get('/', 'Admin\ColocationController@index')->name('index');
        Route::get('/add', 'Admin\ColocationController@create')->name('add');
        Route::post('/add', 'Admin\ColocationController@store');
        Route::get('/show/{id}', 'Admin\ColocationController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\ColocationController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\ColocationController@update');
        Route::get('/delete/{id}', 'Admin\ColocationController@delete')->name('delete');
    });

    Route::prefix('nwall')->name('nwall.')->group(function() {
        Route::get('/', 'Admin\NWallController@index')->name('index');
        Route::get('/add', 'Admin\NWallController@create')->name('add');
        Route::post('/add', 'Admin\NWallController@store');
        Route::get('/show/{id}', 'Admin\NWallController@show')->name('show');
        Route::get('/edit/{id}', 'Admin\NWallController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\NWallController@update');
        Route::get('/delete/{id}', 'Admin\NWallController@delete')->name('delete');
    });

    Route::prefix('seo')->name('seo.')->group(function() {
        Route::get('/', 'Admin\SeoController@index')->name('index');
        Route::get('/add', 'Admin\SeoController@create')->name('add');
        Route::post('/add', 'Admin\SeoController@store');
        Route::get('/show/{id}', 'Admin\SeoController@show');
        Route::get('/edit/{id}', 'Admin\SeoController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\SeoController@update');
        Route::get('/delete/{id}', 'Admin\SeoController@delete')->name('delete');
    });

    Route::prefix('pages')->name('pages.')->group(function() {
        Route::get('/', 'Admin\PageController@index')->name('index');
        Route::get('/add', 'Admin\PageController@create')->name('add');
        Route::post('/add', 'Admin\PageController@store');
        Route::get('/show/{id}', 'Admin\PageController@show');
        Route::get('/edit/{id}', 'Admin\PageController@edit')->name('edit');
        Route::post('/edit/{id}', 'Admin\PageController@update');
        Route::get('/delete/{id}', 'Admin\PageController@delete')->name('delete');
    });

    Route::prefix('config')->name('config.')->group(function() {
        Route::get('/', 'Admin\ConfigController@index');
        Route::get('/homepage', 'Admin\ConfigController@show_homepage')->name('show_homepage');
        Route::get('/homepage/{id}', 'Admin\ConfigController@edit_homepage')->name('edit_homepage');
        Route::post('/homepage/{id}', 'Admin\ConfigController@update_homepage');
    });
});

routes/web.php
<?php
use App\Http\Controllers\Helper\MAC;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();

Route::get('/mlogin', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/mlogin', 'Auth\LoginController@login');
// Route::get('/mregister', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('/mregister/', 'Auth\RegisterController@register');
// Route::get('/mpassword/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
// Route::post('/mpassword/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
// Route::get('/mpassword/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
// Route::post('/mpassword/reset', 'Auth\ResetPasswordController@reset');
Route::get('/logout', 'AuthController@logout')->name('logout');

include base_path('routes/admin.php');
// include base_path('routes/view.php');



Route::get('/', 'Website\HomeController@index')->name('home');
Route::get('su-kien/du-doan-ty-so-viet-nam-malaysia.html', 'Website\HomeController@event');
Route::get('su-kien/du-doan-ket-qua-viet-nam-malaysia.html', 'Website\HomeController@bongda');
Route::get('su-kien/du-doan-ket-qua-viet-nam-indo.html', 'Website\HomeController@vnindo');
// Route::get('/hosting.html', 'Website\HomeController@hosting');
// Route::get('/vps.html', 'Website\HomeController@hosting');
// Route::get('/dedicated.html', 'Website\HomeController@hosting');
// Route::get('/tu-rack.html', 'Website\HomeController@hosting');
Route::get('/2019/04/17/anti-ddos-la-gi', function() {
    return redirect('https://www.nps.vn/kb/blogs/kien-thuc/anti-ddos/dos-ddos-la-gi-cach-chong-hacker-ddos-nhu-the-nao.html');
});

Route::get('/{slug}.html', 'Website\HomeController@page');
// Route::get('/sitemapnps.xml', 'Website\HomeController@xml');
// $segment = '';
// $page = Request::segment(1);
// if (!empty($page)) {
// 	$segment = MAC::redirect_page($page);

// 	if ($segment->status == 200) {
// 		dd($page);
// 		Route::get('/'.$page, 'Website\HomeController@page')->name('page');
// 	}else{
// 		Route::get('/404');
// 	}
// }else{
// 	Route::get('/404');
// }

app/Http/Controllers/Admin/CatalogController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use Session;
use Illuminate\Support\Str;

class CatalogController extends Controller
{
    public function index()
    {
        $data['list'] = DB::table('catalog')->paginate(10);
        return view('admin.catalog.index', $data);
    }

    public function create()
    {
    	$data['list'] = DB::table('catalog')->select('id', 'name', 'parent_id', 'display')->get();
        return view('admin.catalog.add', $data);
    }

    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|max:200'
        ];

        $messages = config('lang.vi');
        $this->validate($request, $rules, $messages);

        $date_time = date('Y-m-d H:i:s');
		$parent_id = (int) $request->parent;
        $data = [
            'name'     => $request->name,
            'slug'     => Str::slug($request->name, '-'),
            'parent_id' => $parent_id,
            'display'     => $request->display,
            'type'     => $request->type,
            'created_at' => $date_time,
            'updated_at' => $date_time,
        ];
        $check_slug = DB::table('catalog')->where('slug', $data['slug'])->first();
		if (isset($check_slug)) {
			Session::flash('status', 'danger');
            Session::flash('notify', 'Danh mục này đã tồn tại, vui lòng chọn tên khác!');
            return redirect()->route('admin.catalog.add');
		}
        $id = DB::table('catalog')->insertGetId($data);

        if ($id) {
        	if ($parent_id != 0) {
	    		$arr_cate = DB::table('catalog')->where('id', $parent_id)->value('child');
				$arr_cate = explode(',', $arr_cate);
				if (empty($arr_cate)) {
					$catalog_child = [$id];
				}else{
					array_push($arr_cate, $id);
					$catalog_child = $arr_cate;
				}
				$catalog_child = array_unique($catalog_child);
				$catalog_child = implode(',', $catalog_child);
				DB::table('catalog')->where('id', $parent_id)->update(['child' => $catalog_child]);
	    	}
            Session::flash('status', 'success');
            Session::flash('notify', 'Thêm mới danh mục sản phẩm thành công!');
            return redirect()->route('admin.catalog.edit', ['id' => $id]);
        }else{
            Session::flash('status', 'danger');
            Session::flash('notify', 'Thêm mới danh mục sản phẩm không thành công!');
            return redirect()->route('admin.catalog.index');
        }
    }

    public function edit($id)
    {
        $cate = DB::table('catalog')->where('id', $id)->first();
        if (isset($cate)) {
            $data['data'] = $cate;
            $data['list'] = DB::table('catalog')->get();
			if ($cate->child) {
				$data['child'] = explode(',', $cate->child);
			}
            return view('admin.catalog.edit', $data);
        }
        Session::flash('status', 'danger');
        Session::flash('notify', 'Không có danh mục này!');
        return redirect()->route('admin.catalog.index');
    }

    public function update(Request $request, $id)
    {
       $cate = DB::table('catalog')->where('id', $id)->first();
        if (isset($cate)) {
            $rules = [
                'name'              => 'required|max:200',
            ];
            $messages = config('lang.vi');
            $date_time = date('Y-m-d H:i:s');
			$parent_id = (int) $request->parent;
            $data = [
	            'name'     	=> $request->name,
	            'slug'     	=> Str::slug($request->name, '-'),
	            'parent_id' => $parent_id,
	            'display'   => $request->display,
                'type'     => $request->type,
	            'child'		=> $request->cate_child,
	            'updated_at' => $date_time,
	        ];

            $this->validate($request, $rules, $messages);
            $function = DB::table('catalog')->where('id', $id)->update($data);
            if ($function) {
            	if ($parent_id != 0) {
		    		$arr_cate = DB::table('catalog')->where('id', $parent_id)->value('child');
					$arr_cate = explode(',', $arr_cate);
					if (empty($arr_cate)) {
						$catalog_child = [$id];
					}else{
						array_push($arr_cate, $id);
						$catalog_child = $arr_cate;
					}
					$catalog_child = array_unique($catalog_child);
					$catalog_child = implode(',', $catalog_child);
					DB::table('catalog')->where('id', $parent_id)->update(['child' => $catalog_child]);
		    	}
                Session::flash('status', 'success');
                Session::flash('notify', 'Cập nhật thông tin danh mục thành công!');
            }else{
                Session::flash('status', 'danger');
                Session::flash('notify', 'Cập nhật thông tin danh mục không thành công!');
            }
            return redirect()->route('admin.catalog.edit', ['id' => $id]);
        }
        Session::flash('status', 'danger');
        Session::flash('notify', 'Không có danh mục này!');
        return redirect()->route('admin.catalog.index');
    }

    public function delete($id)
    {
        $catalog = DB::table('catalog')->where('id', $id)->where('count_product', 0)->first();
        if (isset($catalog)) {
        	$child = explode(',', $catalog->child);
			if (isset($child)) {
				Session::flash('status', 'success');
                Session::flash('notify', 'Vui lòng di chuyển những danh mục con ra khỏi danh mục này rồi hãy xóa!');
				return redirect()->route('admin.catalog.index');
			}
            $function = DB::table('catalog')->where('id', $id)->delete();
            if ($function) {
                Session::flash('status', 'success');
                Session::flash('notify', 'Xóa danh mục sản phẩm thành công!');
            }else{
                Session::flash('status', 'danger');
                Session::flash('notify', 'Xóa danh mục sản phẩm không thành công!');
            }
            return redirect()->route('admin.catalog.index');
        }
        Session::flash('status', 'danger');
        Session::flash('notify', 'Không có danh mục này!');
        return redirect()->route('admin.catalog.index');
    }
}

resources/views/admin/catalog/add.blade.php
@extends('admin.home')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Thêm mới danh mục sản phẩm</h4>
						</div>
					</div>
				</div>
				@include('admin.notify')
				<div class="card-body">
					<form action="" method="post" accept-charset="utf-8">
						@csrf
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Name</label>
								<input type="text" name="name" class="form-control input_mac" value="{{ old('name') }}" required="" maxlength="200">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<label class="label_mac">Link</label>
								<input type="text" name="slug" class="form-control input_mac" value="{{ old('link') }}" disabled="">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-4 pl-0 form_mac">
								<select name="parent" class="form-control select_mac">
									<option value="0" >No Parent</option>
									@foreach ($list as $item)
										@if ($item->display == 1 && $item->parent_id == 0)
										<option value="{{ $item->id }}" >{{ $item->name }}</option>
										@endif
									@endforeach
								</select>
							</div>
							<div class="col-md-4 form_mac">
								<select name="display" class="form-control select_mac">
									<option value="0" >Hide</option>
									<option value="1" selected>Show</option>
								</select>
							</div>
							<div class="col-md-4 pr-0 form_mac">
								<select name="type" class="form-control select_mac">
									@foreach (config('product.type') as $item)
									<option value="{{ $item }}" selected>{{ $item }}</option>
									@endforeach
								</select>
							</div>
						</div>
						<div class="form-group text-right">
							<button type="submit" class="btn">Thêm mới</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		
		$('[name="name"]').keyup(function() {
			$('[name="slug"]').parent('.form_mac').children('.label_mac').css({'top':'-20px', 'font-size':'11px', 'transition-duration':'0.3s'});
			slug = $('[name="name"]').val();
			slug = replace_vi(slug);
			slug = slug.replace(/\s/gi,'-');
			console.log(slug)
			$('[name="slug"]').val(slug);
		});
	});
</script>
@endsection

resources/views/admin/catalog/edit.blade.php
@php
	use App\Http\Controllers\Helper\MAC;
@endphp
@extends('admin.home')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Cập nhật thông tin danh mục</h4>
						</div>
					</div>
				</div>
				@include('admin.notify')
				<div class="card-body">
					<form action="" method="post" accept-charset="utf-8">
						@csrf
						<div class="form-group row">
							<div class="col-md-6 pl-0 form_mac">
								<label class="label_mac">Name</label>
								<input type="text" name="name" class="form-control input_mac" value="{{ $data->name }}" required="" maxlength="200">
							</div>
							<div class="col-md-6 pr-0 form_mac">
								<label class="label_mac">Link</label>
								<input type="text" name="slug" class="form-control input_mac" value="{{ $data->slug }}" disabled="">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-4 pl-0 form_mac">
								<select name="parent" class="form-control select_mac">
									<option value="0" >No Parent</option>
									@foreach ($list as $item)
										@if ($item->display == 1 && $item->parent_id == 0 && $item->id != $data->id)
										<option value="{{ $item->id }}" {{ ($item->id == $data->parent_id) ? 'selected' : '' }}>{{ $item->name }}</option>
										@endif
									@endforeach
								</select>
							</div>
							<div class="col-md-4 form_mac">
								<select name="display" class="form-control select_mac">
									<option value="0" {{ ($data->display == 0) ? 'selected' : '' }}>Hide</option>
									<option value="1" {{ ($data->display == 1) ? 'selected' : '' }}>Show</option>
								</select>
							</div>
							<div class="col-md-4 pr-0 form_mac">
								<select name="type" class="form-control select_mac">
									@foreach (config('product.type') as $item)
									<option value="{{ $item }}" {{ ($item == $data->type) ? 'selected' : '' }}>{{ $item }}</option>
									@endforeach
								</select>
							</div>
						</div>
						<div class="form-group text-right">
							<input type="text" name="cate_child" value="{{ $data->child }}" class="d-none">
							<button type="submit" class="btn">Cập nhật</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	@if (!empty($child))
	<div class="row pt-5">
		<div class="col-md-3">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Danh sách danh mục con</h4>
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach ($child as $item)
					<div class="custom-control custom-checkbox pr-5">
						<input type="checkbox" class="custom-control-input child_checkbox" value="{{ $item }}" id="{{ $item }}_checkbox" checked="">
						<label class="custom-control-label" for="{{ $item }}_checkbox">{{ strtoupper(MAC::cateColInList($item, $list, 'name')) }}</label>
					</div>
					@endforeach
				</div>
			</div>
		</div>
	</div>
	@endif
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('[name="name"]').keyup(function() {
			$('[name="slug"]').parent('.form_mac').children('.label_mac').css({'top':'-20px', 'font-size':'11px', 'transition-duration':'0.3s'});
			slug = $('[name="name"]').val();
			slug = replace_vi(slug);
			slug = slug.replace(/\s/gi,'-');
			console.log(slug)
			$('[name="slug"]').val(slug);
		});

		

		$('.child_checkbox').change(function() {
			all_checkbox = $('.child_checkbox:checked');
			arr = [];
			all_checkbox.each(function() {
				arr.push($(this).val());
			});
			$('[name="cate_child"]').val(arr.toString());
		});
	});
</script>
@endsection

resources/views/admin/catalog/index.blade.php
@php
	use App\Http\Controllers\Helper\MAC;
@endphp
@extends('admin.home')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-4 card_title">
							<h4>Danh sách danh mục sản phẩm</h4>
						</div>
						<div class="col-md-4 text-center btn_add">
							<a href="{{ route('admin.catalog.add') }}"><i class="fas fa-plus"></i></a>
						</div>
						<div class="col-md-4 card_search">
							<form action="" method="post" accept-charset="utf-8" class="">
								@csrf
								<div class="input-group justify-content-end">
									<input type="text" class="form-control input_search" name="" value="" placeholder="Search">
									<button type="submit" class="btn btn-white"><i class="fas fa-search"></i></button>
								</div>
							</form>
						</div>
					</div>
				</div>
				@include('admin.notify')
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-hover table-striped">
							<thead>
								<tr>
									<th>ID</th>
									<th>Name</th>
									<th>Parent</th>
									<th>Count Product</th>
									<th>Created Date</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								@foreach (@$list as $item)
								<tr>
									<td>{{ @$item->id }}</td>
									<td><a href="{{ route('admin.catalog.edit', ['id' => $item->id]) }}" class="px-0">{{ @$item->name }}</a></td>
									<td>{{ MAC::cateColInList($item->parent_id, $list, 'name') }}</td>
									<td>{{ @$item->count_product }}</td>
									<td>{{ @$item->created_at }}</td>
									<td>
										<a href="{{ route('admin.catalog.edit', ['id' => $item->id]) }}"><i class="fas fa-edit"></i></a>
										<a href="{{ route('admin.catalog.delete', ['id' => $item->id]) }}" onclick="return confirm('Bạn có chắn chắn muốn xóa danh mục sản phẩm: {{ @$item->name }} không?');"><i class="fas fa-trash-alt"></i></a>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
						{{ $list->links() }}
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row pt-5">
		<div class="col-md-4">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Menu Top</h4>
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach ($list as $item)
						@if ($item->display == 1 && @in_array('menu_top', json_decode($item->location)) && $item->parent_id == 0)
							<div class="category_parent category_show">
								<p>{{ $item->name }}</p>
							</div>
							@if (!empty($item->child))
								@foreach (explode(',', $item->child) as $val)
									<div class="category_child category_show">
										<p>{{ MAC::cateColInList($val, $list, 'name') }}</p>
									</div>
								@endforeach
							@endif
						@endif
					@endforeach
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Sidebar</h4>
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach ($list as $item)
						@if ($item->display == 1 && @in_array('sidebar', json_decode($item->location)) && $item->parent_id == 0)
							<div class="category_parent category_show">
								<p>{{ $item->name }}</p>
							</div>
							@if (!empty($item->child))
								@foreach (explode(',', $item->child) as $val)
									<div class="category_child category_show">
										<p>{{ MAC::cateColInList($val, $list, 'name') }}</p>
									</div>
								@endforeach
							@endif
						@endif
					@endforeach
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-12 card_title">
							<h4>Footer</h4>
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach ($list as $item)
						@if ($item->display == 1 && @in_array('footer', json_decode($item->location)) && $item->parent_id == 0)
							<div class="category_parent category_show">
								<p>{{ $item->name }}</p>
							</div>
							@if (!empty($item->child))
								@foreach (explode(',', $item->child) as $val)
									<div class="category_child category_show">
										<p>{{ MAC::cateColInList($val, $list, 'name') }}</p>
									</div>
								@endforeach
							@endif
						@endif
					@endforeach
				</div>
			</div>
		</div>
	</div>
</div>
@endsection